const fn = require('../is-buffer')

test('is-buffer', () => {
  expect(fn(Buffer.from('abc'))).toBe(true)

  expect(fn(Buffer)).toBe(false)
  expect(fn(new Array())).toBe(false)
  expect(fn(new Array(1))).toBe(false)
  expect(fn(new ArrayBuffer(1))).toBe(false)
  expect(fn([])).toBe(false)
  expect(fn([1])).toBe(false)
  expect(fn({})).toBe(false)
  expect(fn(Object.create(null))).toBe(false)
  expect(fn('abc')).toBe(false)
  expect(fn(0)).toBe(false)
  expect(fn(1)).toBe(false)
  expect(fn(true)).toBe(false)
  expect(fn(false)).toBe(false)
  expect(fn(null)).toBe(false)
  expect(fn(undefined)).toBe(false)
  expect(fn(NaN)).toBe(false)
  expect(fn(Infinity)).toBe(false)
  expect(fn(/./)).toBe(false)
  expect(fn(Math)).toBe(false)
  expect(fn(function() {})).toBe(false)
  expect(fn(new Date())).toBe(false)
  expect(fn(arguments)).toBe(false)
})
