const fn = require('../is-string')

test('is-string default behavior', () => {
  expect(fn('abc')).toBe(true)
  expect(fn(' a ')).toBe(true)
  expect(fn('   ')).toBe(true)
  expect(fn('')).toBe(true)

  expect(fn(new String(''))).toBe(false)
  expect(fn(new String('abc'))).toBe(false)
  expect(fn([])).toBe(false)
  expect(fn([1])).toBe(false)
  expect(fn(1)).toBe(false)
  expect(fn(0)).toBe(false)
  expect(fn(true)).toBe(false)
  expect(fn(false)).toBe(false)
  expect(fn(null)).toBe(false)
  expect(fn(undefined)).toBe(false)
  expect(fn(Math)).toBe(false)
  expect(fn(JSON)).toBe(false)
  expect(fn(Set)).toBe(false)
  expect(fn(Map)).toBe(false)
  expect(fn(Int16Array)).toBe(false)
  expect(fn(new Int16Array)).toBe(false)
  expect(fn(Buffer.from('a'))).toBe(false)
  expect(fn(function() {})).toBe(false)
  expect(fn(new Date)).toBe(false)
  expect(fn(arguments)).toBe(false)
})

test('is-string filled', () => {
  expect(fn('abc', true)).toBe(true)
  expect(fn(' a ', true)).toBe(true)

  expect(fn('   ', true)).toBe(false)
  expect(fn('', true)).toBe(false)
  expect(fn(new String(''), true)).toBe(false)
  expect(fn(new String('abc'), true)).toBe(false)
})
