
const fn = require('..').is
const test = require('tape')

test('default behavior', function (t) {

  t.deepEqual(fn('Array', 12),       false)
  t.deepEqual(fn('Array', []),       false)
  t.deepEqual(fn('  array   ', [1]), true)
  t.deepEqual(fn('array:true', [1]), true)
  t.deepEqual(fn('array:false', []), true)
  t.deepEqual(fn('array:a', []),     false)
  t.deepEqual(fn('array:12', []),    false)

  t.deepEqual(fn('boolean', []),     false)
  t.deepEqual(fn('boolean', 1),      false)
  t.deepEqual(fn('boolean', 0),      false)
  t.deepEqual(fn('boolean', true),   true)
  t.deepEqual(fn('boolean', false),  true)
  t.deepEqual(fn('boolean:true', false),   true)
  t.deepEqual(fn('boolean:false', false),  true)
  t.deepEqual(fn('boolean:a', false),      true)
  t.deepEqual(fn('boolean:12', false),     true)

  t.deepEqual(fn('defined', ''),          false)
  t.deepEqual(fn('defined', ' '),         false)
  t.deepEqual(fn('defined:true', ' '),    false)
  t.deepEqual(fn('defined:false', ' '),   false)
  t.deepEqual(fn('defined:a', ' '),       false)
  t.deepEqual(fn('defined:12', ' '),      false)
  t.deepEqual(fn('defined', 'a'),         true)
  t.deepEqual(fn('defined', []),          false)
  t.deepEqual(fn('defined', [1]),         true)
  t.deepEqual(fn('defined', {}),          false)
  t.deepEqual(fn('defined', {a:1}),       true)
  t.deepEqual(fn('defined:true', {a:1}),  true)
  t.deepEqual(fn('defined:false', {a:1}), true)
  t.deepEqual(fn('defined:a', {a:1}),     true)
  t.deepEqual(fn('defined:12', {a:1}),    true)

  t.deepEqual(fn('float', {a:1}),      false)
  t.deepEqual(fn('float', 1),          false)
  t.deepEqual(fn('float', 0),          false)
  t.deepEqual(fn('float', 1.1),        true)
  t.deepEqual(fn('float', -1.1),       true)
  t.deepEqual(fn('float:true', -1.1),  true)
  t.deepEqual(fn('float:false', -1.1), true)
  t.deepEqual(fn('float:a', -1.1),     true)
  t.deepEqual(fn('float:12', -1.1),    true)

  var max = Math.max
  var noop = function() {}
  t.deepEqual(fn('function', null),       false)
  t.deepEqual(fn('function', [1]),        false)
  t.deepEqual(fn('function', Math),       false)
  t.deepEqual(fn('function', max),        true)
  t.deepEqual(fn('function', noop),       true)
  t.deepEqual(fn('function:true', noop),  true)
  t.deepEqual(fn('function:false', noop), true)
  t.deepEqual(fn('function:a', noop),     true)
  t.deepEqual(fn('function:12', noop),    true)

  t.deepEqual(fn('integer', {a:1}),      false)
  t.deepEqual(fn('integer', 1),          true)
  t.deepEqual(fn('integer', 0),          true)
  t.deepEqual(fn('integer', 1.1),        false)
  t.deepEqual(fn('integer', -1.1),       false)
  t.deepEqual(fn('integer:true', -1.1),  false)
  t.deepEqual(fn('integer:false', -1.1), false)
  t.deepEqual(fn('integer:a', -1.1),     false)
  t.deepEqual(fn('integer:12', -1.1),    false)

  t.deepEqual(fn('node', 'abc'),      false)
  t.deepEqual(fn('node', {a:1}),      false)
  t.deepEqual(fn('node', -1.1),       false)
  t.deepEqual(fn('node:true', -1.1),  false)
  t.deepEqual(fn('node:false', -1.1), false)
  t.deepEqual(fn('node:a', -1.1),     false)
  t.deepEqual(fn('node:12', -1.1),    false)

  t.deepEqual(fn('number', {a:1}),      false)
  t.deepEqual(fn('number', NaN),        false)
  t.deepEqual(fn('number', 1),          true)
  t.deepEqual(fn('number', 0),          true)
  t.deepEqual(fn('number', 1.1),        true)
  t.deepEqual(fn('number', -1.1),       true)
  t.deepEqual(fn('number:true', -1.1),  true)
  t.deepEqual(fn('number:false', -1.1), true)
  t.deepEqual(fn('number:true',  NaN),  false)
  t.deepEqual(fn('number:false', NaN),  true)
  t.deepEqual(fn('number:a', NaN),      false)
  t.deepEqual(fn('number:a', -1.1),     true)
  t.deepEqual(fn('number:12', -1.1),    true)

  t.deepEqual(fn('object', ''),          false)
  t.deepEqual(fn('object', ' '),         false)
  t.deepEqual(fn('object', 'a'),         false)
  t.deepEqual(fn('object', []),          false)
  t.deepEqual(fn('object', [1]),         false)
  t.deepEqual(fn('object', {}),          false)
  t.deepEqual(fn('object', {a:1}),       true)
  t.deepEqual(fn('object:true', {}),     false)
  t.deepEqual(fn('object:false', {}),    true)
  t.deepEqual(fn('object:a', {}),        false)
  t.deepEqual(fn('object:12', {}),       false)
  t.deepEqual(fn('object', {a:1}),       true)
  t.deepEqual(fn('object:true', {a:1}),  true)
  t.deepEqual(fn('object:false', {a:1}), true)
  t.deepEqual(fn('object:a', {a:1}),     true)
  t.deepEqual(fn('object:12', {a:1}),    true)

  t.deepEqual(fn('string', ''),        false)
  t.deepEqual(fn('string', ' '),       false)
  t.deepEqual(fn('string', 'a'),       true)
  t.deepEqual(fn('string', []),        false)
  t.deepEqual(fn('string', [1]),       false)
  t.deepEqual(fn('string', {}),        false)
  t.deepEqual(fn('string', {a:1}),     false)
  t.deepEqual(fn('string:true', ' '),  false)
  t.deepEqual(fn('string:false', ' '), true)
  t.deepEqual(fn('string:a', ' '),     false)
  t.deepEqual(fn('string:12', ' '),    false)
  t.deepEqual(fn('string:true', 'a'),  true)
  t.deepEqual(fn('string:false', 'a'), true)
  t.deepEqual(fn('string:a', 'a'),     true)
  t.deepEqual(fn('string:12', 'a'),    true)

  t.deepEqual(fn('lt:', -1.1),       false)
  t.deepEqual(fn('lt:a', -1.1),      false)
  t.deepEqual(fn('lt:true', -1.1),   false)
  t.deepEqual(fn('lt:false', -1.1),  false)
  t.deepEqual(fn('lt:-0.1.', -1.1),  false)
  t.deepEqual(fn('lt:-1.1.', -1.1),  false)
  t.deepEqual(fn('lt:-1.1',  -1.1),  false)
  t.deepEqual(fn('lt:3',  -1.1),     true)

  t.deepEqual(fn('lte:', -1.1),      false)
  t.deepEqual(fn('lte:a', -1.1),     false)
  t.deepEqual(fn('lte:true', -1.1),  false)
  t.deepEqual(fn('lte:false', -1.1), false)
  t.deepEqual(fn('lte:-1.1', -1.1),  true)
  t.deepEqual(fn('lte:-1.1', -1),    false)
  t.deepEqual(fn('lte:-1.1', -1.11), true)
  t.deepEqual(fn('lte:-1.1', -1.1),  true)

  t.deepEqual(fn('gt:', -1.1),       false)
  t.deepEqual(fn('gt:a', -1.1),      false)
  t.deepEqual(fn('gt:true', -1.1),   false)
  t.deepEqual(fn('gt:false', -1.1),  false)
  t.deepEqual(fn('gt:-0.1.', -1.1),  false)
  t.deepEqual(fn('gt:-1.1.', -1.1),  false)
  t.deepEqual(fn('gt:-1.1',  -1.1),  false)
  t.deepEqual(fn('gt:-1.2',  -1.1),  true)

  t.deepEqual(fn('gte:', -1.1),      false)
  t.deepEqual(fn('gte:a', -1.1),     false)
  t.deepEqual(fn('gte:true', -1.1),  false)
  t.deepEqual(fn('gte:false', -1.1), false)
  t.deepEqual(fn('gte:-1.1', -1.1),  true)
  t.deepEqual(fn('gte:-1.1', -1),    true)
  t.deepEqual(fn('gte:-1.1', -1.11), false)
  t.deepEqual(fn('gte:-1.1', -1.09), true)

  t.deepEqual(fn('number float gte:-1.1', -1.09), true)
  t.deepEqual(fn('array defined', [1]),           true)
  t.deepEqual(fn('number float gte:-1.1', -2),    false)
  t.deepEqual(fn('float lte:1 gte:-1', -0.09),    true)
  t.deepEqual(fn('float lte:1 gte:-1', -1),       false)
  t.deepEqual(fn('number integer defined gte:-1.1', -1),       true)
  t.deepEqual(fn('  number  integer defined   gte:-1.1 ', -1), true)

  t.end()
})
